// Code generated by protoc-gen-connect-go.exe. DO NOT EDIT.
//
// Source: pkg/ToDo/presenter/todo.proto

package presenterconnect

import (
	presenter "SweetheartSuite/v2/pkg/ToDo/presenter"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// ToDoName is the fully-qualified name of the ToDo service.
	ToDoName = "SweetheartSuite.v2.ToDo"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ToDoAddItemProcedure is the fully-qualified name of the ToDo's AddItem RPC.
	ToDoAddItemProcedure = "/SweetheartSuite.v2.ToDo/AddItem"
	// ToDoAddListProcedure is the fully-qualified name of the ToDo's AddList RPC.
	ToDoAddListProcedure = "/SweetheartSuite.v2.ToDo/AddList"
	// ToDoGetItemsByIdsProcedure is the fully-qualified name of the ToDo's GetItemsByIds RPC.
	ToDoGetItemsByIdsProcedure = "/SweetheartSuite.v2.ToDo/GetItemsByIds"
	// ToDoGetItemsByCoupleProcedure is the fully-qualified name of the ToDo's GetItemsByCouple RPC.
	ToDoGetItemsByCoupleProcedure = "/SweetheartSuite.v2.ToDo/GetItemsByCouple"
	// ToDoUpdateItemProcedure is the fully-qualified name of the ToDo's UpdateItem RPC.
	ToDoUpdateItemProcedure = "/SweetheartSuite.v2.ToDo/UpdateItem"
	// ToDoDeleteItemProcedure is the fully-qualified name of the ToDo's DeleteItem RPC.
	ToDoDeleteItemProcedure = "/SweetheartSuite.v2.ToDo/DeleteItem"
)

// ToDoClient is a client for the SweetheartSuite.v2.ToDo service.
type ToDoClient interface {
	AddItem(context.Context, *connect.Request[presenter.AddItemRequest]) (*connect.Response[presenter.AddItemResponse], error)
	AddList(context.Context, *connect.Request[presenter.AddListRequest]) (*connect.Response[presenter.AddListResponse], error)
	GetItemsByIds(context.Context, *connect.Request[presenter.GetItemsByIdsRequest]) (*connect.Response[presenter.GetItemsByIdsResponse], error)
	GetItemsByCouple(context.Context, *connect.Request[presenter.GetItemsByCoupleRequest]) (*connect.Response[presenter.GetItemsByCoupleResponse], error)
	UpdateItem(context.Context, *connect.Request[presenter.UpdateItemRequest]) (*connect.Response[presenter.UpdateItemResponse], error)
	DeleteItem(context.Context, *connect.Request[presenter.DeleteItemRequest]) (*connect.Response[presenter.DeleteItemResponse], error)
}

// NewToDoClient constructs a client for the SweetheartSuite.v2.ToDo service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewToDoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ToDoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &toDoClient{
		addItem: connect.NewClient[presenter.AddItemRequest, presenter.AddItemResponse](
			httpClient,
			baseURL+ToDoAddItemProcedure,
			opts...,
		),
		addList: connect.NewClient[presenter.AddListRequest, presenter.AddListResponse](
			httpClient,
			baseURL+ToDoAddListProcedure,
			opts...,
		),
		getItemsByIds: connect.NewClient[presenter.GetItemsByIdsRequest, presenter.GetItemsByIdsResponse](
			httpClient,
			baseURL+ToDoGetItemsByIdsProcedure,
			opts...,
		),
		getItemsByCouple: connect.NewClient[presenter.GetItemsByCoupleRequest, presenter.GetItemsByCoupleResponse](
			httpClient,
			baseURL+ToDoGetItemsByCoupleProcedure,
			opts...,
		),
		updateItem: connect.NewClient[presenter.UpdateItemRequest, presenter.UpdateItemResponse](
			httpClient,
			baseURL+ToDoUpdateItemProcedure,
			opts...,
		),
		deleteItem: connect.NewClient[presenter.DeleteItemRequest, presenter.DeleteItemResponse](
			httpClient,
			baseURL+ToDoDeleteItemProcedure,
			opts...,
		),
	}
}

// toDoClient implements ToDoClient.
type toDoClient struct {
	addItem          *connect.Client[presenter.AddItemRequest, presenter.AddItemResponse]
	addList          *connect.Client[presenter.AddListRequest, presenter.AddListResponse]
	getItemsByIds    *connect.Client[presenter.GetItemsByIdsRequest, presenter.GetItemsByIdsResponse]
	getItemsByCouple *connect.Client[presenter.GetItemsByCoupleRequest, presenter.GetItemsByCoupleResponse]
	updateItem       *connect.Client[presenter.UpdateItemRequest, presenter.UpdateItemResponse]
	deleteItem       *connect.Client[presenter.DeleteItemRequest, presenter.DeleteItemResponse]
}

// AddItem calls SweetheartSuite.v2.ToDo.AddItem.
func (c *toDoClient) AddItem(ctx context.Context, req *connect.Request[presenter.AddItemRequest]) (*connect.Response[presenter.AddItemResponse], error) {
	return c.addItem.CallUnary(ctx, req)
}

// AddList calls SweetheartSuite.v2.ToDo.AddList.
func (c *toDoClient) AddList(ctx context.Context, req *connect.Request[presenter.AddListRequest]) (*connect.Response[presenter.AddListResponse], error) {
	return c.addList.CallUnary(ctx, req)
}

// GetItemsByIds calls SweetheartSuite.v2.ToDo.GetItemsByIds.
func (c *toDoClient) GetItemsByIds(ctx context.Context, req *connect.Request[presenter.GetItemsByIdsRequest]) (*connect.Response[presenter.GetItemsByIdsResponse], error) {
	return c.getItemsByIds.CallUnary(ctx, req)
}

// GetItemsByCouple calls SweetheartSuite.v2.ToDo.GetItemsByCouple.
func (c *toDoClient) GetItemsByCouple(ctx context.Context, req *connect.Request[presenter.GetItemsByCoupleRequest]) (*connect.Response[presenter.GetItemsByCoupleResponse], error) {
	return c.getItemsByCouple.CallUnary(ctx, req)
}

// UpdateItem calls SweetheartSuite.v2.ToDo.UpdateItem.
func (c *toDoClient) UpdateItem(ctx context.Context, req *connect.Request[presenter.UpdateItemRequest]) (*connect.Response[presenter.UpdateItemResponse], error) {
	return c.updateItem.CallUnary(ctx, req)
}

// DeleteItem calls SweetheartSuite.v2.ToDo.DeleteItem.
func (c *toDoClient) DeleteItem(ctx context.Context, req *connect.Request[presenter.DeleteItemRequest]) (*connect.Response[presenter.DeleteItemResponse], error) {
	return c.deleteItem.CallUnary(ctx, req)
}

// ToDoHandler is an implementation of the SweetheartSuite.v2.ToDo service.
type ToDoHandler interface {
	AddItem(context.Context, *connect.Request[presenter.AddItemRequest]) (*connect.Response[presenter.AddItemResponse], error)
	AddList(context.Context, *connect.Request[presenter.AddListRequest]) (*connect.Response[presenter.AddListResponse], error)
	GetItemsByIds(context.Context, *connect.Request[presenter.GetItemsByIdsRequest]) (*connect.Response[presenter.GetItemsByIdsResponse], error)
	GetItemsByCouple(context.Context, *connect.Request[presenter.GetItemsByCoupleRequest]) (*connect.Response[presenter.GetItemsByCoupleResponse], error)
	UpdateItem(context.Context, *connect.Request[presenter.UpdateItemRequest]) (*connect.Response[presenter.UpdateItemResponse], error)
	DeleteItem(context.Context, *connect.Request[presenter.DeleteItemRequest]) (*connect.Response[presenter.DeleteItemResponse], error)
}

// NewToDoHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewToDoHandler(svc ToDoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	toDoAddItemHandler := connect.NewUnaryHandler(
		ToDoAddItemProcedure,
		svc.AddItem,
		opts...,
	)
	toDoAddListHandler := connect.NewUnaryHandler(
		ToDoAddListProcedure,
		svc.AddList,
		opts...,
	)
	toDoGetItemsByIdsHandler := connect.NewUnaryHandler(
		ToDoGetItemsByIdsProcedure,
		svc.GetItemsByIds,
		opts...,
	)
	toDoGetItemsByCoupleHandler := connect.NewUnaryHandler(
		ToDoGetItemsByCoupleProcedure,
		svc.GetItemsByCouple,
		opts...,
	)
	toDoUpdateItemHandler := connect.NewUnaryHandler(
		ToDoUpdateItemProcedure,
		svc.UpdateItem,
		opts...,
	)
	toDoDeleteItemHandler := connect.NewUnaryHandler(
		ToDoDeleteItemProcedure,
		svc.DeleteItem,
		opts...,
	)
	return "/SweetheartSuite.v2.ToDo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ToDoAddItemProcedure:
			toDoAddItemHandler.ServeHTTP(w, r)
		case ToDoAddListProcedure:
			toDoAddListHandler.ServeHTTP(w, r)
		case ToDoGetItemsByIdsProcedure:
			toDoGetItemsByIdsHandler.ServeHTTP(w, r)
		case ToDoGetItemsByCoupleProcedure:
			toDoGetItemsByCoupleHandler.ServeHTTP(w, r)
		case ToDoUpdateItemProcedure:
			toDoUpdateItemHandler.ServeHTTP(w, r)
		case ToDoDeleteItemProcedure:
			toDoDeleteItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedToDoHandler returns CodeUnimplemented from all methods.
type UnimplementedToDoHandler struct{}

func (UnimplementedToDoHandler) AddItem(context.Context, *connect.Request[presenter.AddItemRequest]) (*connect.Response[presenter.AddItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("SweetheartSuite.v2.ToDo.AddItem is not implemented"))
}

func (UnimplementedToDoHandler) AddList(context.Context, *connect.Request[presenter.AddListRequest]) (*connect.Response[presenter.AddListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("SweetheartSuite.v2.ToDo.AddList is not implemented"))
}

func (UnimplementedToDoHandler) GetItemsByIds(context.Context, *connect.Request[presenter.GetItemsByIdsRequest]) (*connect.Response[presenter.GetItemsByIdsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("SweetheartSuite.v2.ToDo.GetItemsByIds is not implemented"))
}

func (UnimplementedToDoHandler) GetItemsByCouple(context.Context, *connect.Request[presenter.GetItemsByCoupleRequest]) (*connect.Response[presenter.GetItemsByCoupleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("SweetheartSuite.v2.ToDo.GetItemsByCouple is not implemented"))
}

func (UnimplementedToDoHandler) UpdateItem(context.Context, *connect.Request[presenter.UpdateItemRequest]) (*connect.Response[presenter.UpdateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("SweetheartSuite.v2.ToDo.UpdateItem is not implemented"))
}

func (UnimplementedToDoHandler) DeleteItem(context.Context, *connect.Request[presenter.DeleteItemRequest]) (*connect.Response[presenter.DeleteItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("SweetheartSuite.v2.ToDo.DeleteItem is not implemented"))
}
