// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: pkg/ToDo/presenter/todo.proto

package presenter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoupleId    string `protobuf:"bytes,1,opt,name=coupleId,proto3" json:"coupleId,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{0}
}

func (x *AddItemRequest) GetCoupleId() string {
	if x != nil {
		return x.CoupleId
	}
	return ""
}

func (x *AddItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type AddListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoupleId string `protobuf:"bytes,1,opt,name=coupleId,proto3" json:"coupleId,omitempty"`
}

func (x *AddListRequest) Reset() {
	*x = AddListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListRequest) ProtoMessage() {}

func (x *AddListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListRequest.ProtoReflect.Descriptor instead.
func (*AddListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{2}
}

func (x *AddListRequest) GetCoupleId() string {
	if x != nil {
		return x.CoupleId
	}
	return ""
}

type AddListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId string `protobuf:"bytes,1,opt,name=listId,proto3" json:"listId,omitempty"`
}

func (x *AddListResponse) Reset() {
	*x = AddListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListResponse) ProtoMessage() {}

func (x *AddListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListResponse.ProtoReflect.Descriptor instead.
func (*AddListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{3}
}

func (x *AddListResponse) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId string `protobuf:"bytes,1,opt,name=listId,proto3" json:"listId,omitempty"`
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type GetItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId      string `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsDone      bool   `protobuf:"varint,4,opt,name=isDone,proto3" json:"isDone,omitempty"`
	DoneDate    string `protobuf:"bytes,5,opt,name=doneDate,proto3" json:"doneDate,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ToDo_presenter_todo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_pkg_ToDo_presenter_todo_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *Item) GetDoneDate() string {
	if x != nil {
		return x.DoneDate
	}
	return ""
}

var File_pkg_ToDo_presenter_todo_proto protoreflect.FileDescriptor

var file_pkg_ToDo_presenter_todo_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x54, 0x6f, 0x44, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x53, 0x77, 0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65,
	0x2e, 0x76, 0x32, 0x22, 0x64, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x29, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x53, 0x77,
	0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x32,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x8a, 0x01, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x6f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x6f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x32, 0x8b, 0x02, 0x0a, 0x04, 0x54, 0x6f,
	0x44, 0x6f, 0x12, 0x54, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x2e,
	0x53, 0x77, 0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x53, 0x77, 0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75,
	0x69, 0x74, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x53, 0x77, 0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74,
	0x53, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x53, 0x77, 0x65, 0x65, 0x74, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x64, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x23, 0x2e, 0x53, 0x77, 0x65,
	0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x53, 0x77, 0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74,
	0x65, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x53, 0x77, 0x65, 0x65, 0x74,
	0x68, 0x65, 0x61, 0x72, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x54, 0x6f, 0x44, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ToDo_presenter_todo_proto_rawDescOnce sync.Once
	file_pkg_ToDo_presenter_todo_proto_rawDescData = file_pkg_ToDo_presenter_todo_proto_rawDesc
)

func file_pkg_ToDo_presenter_todo_proto_rawDescGZIP() []byte {
	file_pkg_ToDo_presenter_todo_proto_rawDescOnce.Do(func() {
		file_pkg_ToDo_presenter_todo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ToDo_presenter_todo_proto_rawDescData)
	})
	return file_pkg_ToDo_presenter_todo_proto_rawDescData
}

var file_pkg_ToDo_presenter_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_ToDo_presenter_todo_proto_goTypes = []interface{}{
	(*AddItemRequest)(nil),   // 0: SweetheartSuite.v2.AddItemRequest
	(*AddItemResponse)(nil),  // 1: SweetheartSuite.v2.AddItemResponse
	(*AddListRequest)(nil),   // 2: SweetheartSuite.v2.AddListRequest
	(*AddListResponse)(nil),  // 3: SweetheartSuite.v2.AddListResponse
	(*GetItemsRequest)(nil),  // 4: SweetheartSuite.v2.GetItemsRequest
	(*GetItemsResponse)(nil), // 5: SweetheartSuite.v2.GetItemsResponse
	(*Item)(nil),             // 6: SweetheartSuite.v2.Item
}
var file_pkg_ToDo_presenter_todo_proto_depIdxs = []int32{
	6, // 0: SweetheartSuite.v2.GetItemsResponse.items:type_name -> SweetheartSuite.v2.Item
	0, // 1: SweetheartSuite.v2.ToDo.AddItem:input_type -> SweetheartSuite.v2.AddItemRequest
	2, // 2: SweetheartSuite.v2.ToDo.AddList:input_type -> SweetheartSuite.v2.AddListRequest
	4, // 3: SweetheartSuite.v2.ToDo.GetItems:input_type -> SweetheartSuite.v2.GetItemsRequest
	1, // 4: SweetheartSuite.v2.ToDo.AddItem:output_type -> SweetheartSuite.v2.AddItemResponse
	3, // 5: SweetheartSuite.v2.ToDo.AddList:output_type -> SweetheartSuite.v2.AddListResponse
	5, // 6: SweetheartSuite.v2.ToDo.GetItems:output_type -> SweetheartSuite.v2.GetItemsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_ToDo_presenter_todo_proto_init() }
func file_pkg_ToDo_presenter_todo_proto_init() {
	if File_pkg_ToDo_presenter_todo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ToDo_presenter_todo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ToDo_presenter_todo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ToDo_presenter_todo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ToDo_presenter_todo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ToDo_presenter_todo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ToDo_presenter_todo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ToDo_presenter_todo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ToDo_presenter_todo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ToDo_presenter_todo_proto_goTypes,
		DependencyIndexes: file_pkg_ToDo_presenter_todo_proto_depIdxs,
		MessageInfos:      file_pkg_ToDo_presenter_todo_proto_msgTypes,
	}.Build()
	File_pkg_ToDo_presenter_todo_proto = out.File
	file_pkg_ToDo_presenter_todo_proto_rawDesc = nil
	file_pkg_ToDo_presenter_todo_proto_goTypes = nil
	file_pkg_ToDo_presenter_todo_proto_depIdxs = nil
}
